## EDUNET FOUNDATION - Self-Practice Exercise Notebook

### LAB 8 - Implementing Numpy Concepts in Python

Problem 1: Write a NumPy program to test whether none of the elements of a given array are zero.

Problem 2: Write a NumPy program to create an array of 10 zeros, 10 ones, and 10 fives. 

Problem 3: Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution.

Problem 4: Write a NumPy program to create a two-dimensional array with shape (8,5) of random numbers. Select random numbers from a normal distribution (200,7).

In [40]:
import numpy as np
from numpy import random
array1 = random.choice(8, size=(8,5))
print(array1)


[[4 3 4 6 4]
 [4 1 0 4 5]
 [4 1 2 6 4]
 [3 7 2 1 7]
 [5 7 3 1 5]
 [2 0 0 3 7]
 [6 4 3 6 0]
 [6 6 7 4 1]]


Problem 5: Write a NumPy program to create a 4x4 array. Create an array from said array by swapping first and last, second and third columns.

In [62]:
import numpy as np

# Create a 4x4 empty array
array_empty = np.empty((4, 4))
print(array_empty)

import numpy as np 
nums = np.arange(16, dtype='int').reshape(-1,4)
print(nums)

new_nums = nums[:,::-1]
print(new_nums)

[[4.67296746e-307 1.69121096e-306 1.69118787e-306 4.45059334e-308]
 [1.69120145e-306 6.23053614e-307 2.22522597e-306 1.33511969e-306]
 [1.37962320e-306 9.34604358e-307 9.79101082e-307 1.78020576e-306]
 [1.69119873e-306 2.22522868e-306 1.24611809e-306 8.06632139e-308]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]
 [15 14 13 12]]


Problem 6: Write a NumPy program to swap rows and columns of a given array in reverse order.

Problem 7: Write a NumPy program to multiply two given arrays of the same size element-by-element.

Problem 8: Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.

Problem 9: Write a NumPy program to create a 3x3x3 array with random values.
Expected Output:

[[[ 0.48941799 0.58722213 0.43453926]
[ 0.94497547 0.81081709 0.1510409 ]
[ 0.66657127 0.29494755 0.48047144]]
[[ 0.02287253 0.95232614 0.32264936]
[ 0.67009741 0.25458304 0.16290913]
[ 0.15520198 0.86826529 0.9679322 ]]
[[ 0.13503103 0.02042211 0.24683897]
[ 0.97852158 0.22374748 0.10798856]
[ 0.62032646 0.5893892 0.16958144]]]

Problem 10: Write a Python program to find the maximum and minimum value of a given flattened array.

Problem 11: Write a NumPy program to add, subtract, multiply, divide arguments element-wise.     
Expected Output:
Add:
5.0
Subtract:
-3.0
Multiply:
4.0
Divide:
0.25

Problem 12: Write a NumPy program to get the powers of an array values element-wise.
Note: First array elements raised to powers from second array
Expected Output:
Original array
[0 1 2 3 4 5 6]
First array elements raised to powers from second array, element-wise:
[ 0 1 8 27 64 125 216]

Problem 13: Create a Python project to guess a number that has randomly selected.

Problem 14: Write a NumPy program to create a 2D array with 1 on the border and 0 inside.        
Expected Output:
Original array:
[[ 1. 1. 1. 1. 1.]
...................
[ 1. 1. 1. 1. 1.]]
1 on the border and 0 inside in the array
[[ 1. 1. 1. 1. 1.]
...................
[ 1. 1. 1. 1. 1.]]

Problem 15: Write a NumPy program to append values to the end of an array.                      
Expected Output:
Original array:
[10, 20, 30]
After append values to the end of the array:
[10 20 30 40 50 60 70 80 90]